require "http/server/context"
require "http/client/response"
require "json"

module Alumna
  module Testing
    # A convenient response object that parses the raw IO output
    # generated by the HTTP::Server::Response.
    record AppClientResponse, status : Int32, headers : HTTP::Headers, body : String do
      # Quick helper to parse JSON bodies in tests
      def json : JSON::Any
        JSON.parse(body)
      end
    end

    # A virtual HTTP client that dispatches requests directly to the Alumna router
    # entirely in memory. It skips network binding, sockets, and sleeps.
    class AppClient
      getter app : App
      getter router : Http::Router
      getter default_headers : HTTP::Headers

      def initialize(@app : App, trusted_proxies : App::TrustedProxies = nil)
        @router = Http::Router.new(@app, trusted_proxies)
        @default_headers = HTTP::Headers.new
      end

      def get(path : String, headers : Hash(String, String)? = nil)
        request("GET", path, nil, headers)
      end

      def post(path : String, body : String? = nil, headers : Hash(String, String)? = nil)
        request("POST", path, body, headers)
      end

      def put(path : String, body : String? = nil, headers : Hash(String, String)? = nil)
        request("PUT", path, body, headers)
      end

      def patch(path : String, body : String? = nil, headers : Hash(String, String)? = nil)
        request("PATCH", path, body, headers)
      end

      def delete(path : String, headers : Hash(String, String)? = nil)
        request("DELETE", path, nil, headers)
      end

      def options(path : String, headers : Hash(String, String)? = nil)
        request("OPTIONS", path, nil, headers)
      end

      def request(method : String, path : String, body : String? = nil, headers : Hash(String, String)? = nil) : AppClientResponse
        http_headers = @default_headers.dup
        headers.try &.each { |k, v| http_headers[k] = v }

        # Content-Length is required for the router to parse the body
        if body && !http_headers.has_key?("Content-Length")
          http_headers["Content-Length"] = body.bytesize.to_s
        end

        req = HTTP::Request.new(method, path, http_headers, body)

        # We capture the response into an in-memory IO stream
        io = IO::Memory.new
        res = HTTP::Server::Response.new(io)

        http_ctx = HTTP::Server::Context.new(req, res)

        # Dispatch exactly as the real HTTP::Server block would do
        @router.handle(http_ctx)

        # Flush the response to the IO
        res.close
        io.rewind

        # Parse the raw HTTP protocol string back into a friendly struct
        client_res = HTTP::Client::Response.from_io(io, ignore_body: false)

        AppClientResponse.new(
          status: client_res.status_code,
          headers: client_res.headers,
          body: client_res.body
        )
      end
    end
  end
end
